# .mise.toml - A central manifest for project-specific developer tools.
#
# Mise is a polyglot tool version manager, like asdf.
# It uses this file to declare which tools and versions your project needs.
# When you're in a directory with this file, mise automatically activates
# the specified tool versions.
#
# Learn more at: https://mise.jdx.dev/

[tools]
node = "lts"
go = "latest"
ruby = "latest"

# To add more tools, uncomment and adjust the versions as needed e.g.
# terraform = "latest"
# bun = "latest"
# php = "latest"
# poetry = "latest"
